[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scaling-on-scales"
version = "0.1.0"
description = "A simple mechanism to extract multi-scale features using any vision model"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
authors = [
    { name = "Baifeng Shi", email = "baifeng_shi@berkeley.edu" },
    { name = "Ziyang Wu" },
    { name = "Maolin Mao" },
    { name = "Xin Wang" },
    { name = "Trevor Darrell" },
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = ["einops"]

[project.urls]
Homepage = "https://github.com/KennethEnevoldsen/scaling_on_scales"
Source = "https://github.com/KennethEnevoldsen/scaling_on_scales"
